-- TP7 --

-- UTILISATION DU N-UPLET --
-- 1)
select COUNT(*)
    from FILMS
;

-- 2)
select COUNT(distinct FILMS.CODFILM)
    from JOUENT, ACTEURS, REALISATEURS, FILMS
    where NACT = CODACT
    and JOUENT.CODFILM = FILMS.CODFILM
    and FILMS.CODREAL = REALISATEURS.CODREAL
    and NOMREAL = 'Cameron'
    and DNAISSACT > '31/12/1970'
    and SEXE = 'F'
;

-- 3)
select COUNT(distinct NACT)
    from JOUENT, FILMS, REALISATEURS
    where JOUENT.CODFILM = FILMS.CODFILM
    and FILMS.CODREAL = REALISATEURS.CODREAL
    and NOMREAL = 'Cameron'
;

-- 4)
select MAX(BUDGET)
    from FILMS
;

-- 5)
select TITREFILM
    from FILMS
    where BUDGET = (select MAX(BUDGET)from FILMS)
;

-- 6)
select SUM(BUDGET)
    from FILMS, REALISATEURS
    where FILMS.CODREAL = REALISATEURS.CODREAL
    and NOMREAL = 'Cameron'
;

-- UTILISATION DU GROUP BY --
-- 1)
select REALISATEURS.CODREAL, NOMREAL, COUNT(CODFILM)
    from FILMS, REALISATEURS
    where FILMS.CODREAL = REALISATEURS.CODREAL
group by REALISATEURS.CODREAL, NOMREAL
;

-- 2)
select NOMREAL, NATIONREAL, COUNT(distinct NACT)
    from REALISATEURS, FILMS, JOUENT
    where FILMS.CODREAL = REALISATEURS.CODREAL
    and FILMS.CODFILM = JOUENT.CODFILM
group by REALISATEURS.CODREAL, NOMREAL, NATIONREAL
;

-- 3)
select NOMREAL, NATIONREAL, SUM(BUDGET)
    from REALISATEURS, FILMS
    where FILMS.CODREAL = REALISATEURS.CODREAL
    and CATEGORIE = 'science fiction'
group by REALISATEURS.CODREAL, NOMREAL, NATIONREAL
;

-- 4)
select NOMREAL, NATIONREAL, CATEGORIE, COUNT(CODFILM)
    from REALISATEURS, FILMS
    where FILMS.CODREAL = REALISATEURS.CODREAL
group by REALISATEURS.CODREAL, NOMREAL, NATIONREAL, CATEGORIE
;

-- UTILISATION DU HAVING --
-- 1)
select NOMACT, PRENOMACT
    from JOUENT, ACTEURS
    where NACT = CODACT
    and NATIONACT = 'Américaine'
group by CODACT, NOMACT, PRENOMACT
having COUNT(CODFILM) > 2
;

-- 2)
select NOMREAL, NATIONREAL
    from FILMS, REALISATEURS
    where FILMS.CODREAL = REALISATEURS.CODREAL
    and CATEGORIE = 'science fiction'
group by REALISATEURS.CODREAL, NOMREAL, NATIONREAL
having SUM(BUDGET) > 1000000
;

-- 3)
select NOMACT, PRENOMACT
    from ACTEURS, JOUENT
    where NACT = CODACT
group by CODACT, NOMACT, PRENOMACT
having COUNT(CODFILM) > (select COUNT(CODFILM)
    from JOUENT, ACTEURS
    where NACT = CODACT
    and NOMACT = 'Winslet'
    and PRENOMACT = 'Kate')
;

-- 4)
select NOMACT, PRENOMACT
    from ACTEURS, JOUENT
    where NACT = CODACT
group by CODACT, NOMACT, PRENOMACT
having COUNT(CODFILM) = (select MAX(COUNT(CODFILM))
    from JOUENT
group by NACT)
;